---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: client-deployment
spec:
        replicas: 2
        selector:
                matchLabels:
                        component: web
        template:
                metadata:
                        labels:
                                component: web
                spec:
                        containers:
                                - name: client
                                  image: swastiksuman/springboot-docker-webapp
                                  ports:
                                        - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: client-deployment-service
  labels:
    app: client-deployment
spec:
  selector:
    app: client-deployment
  ports:
    - name: http
        port: 8080
        target: 8080

---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: client-deployment-ingress
spec:
  backend:
    serviceName: client-deployment-service
    servicePort: 8080          
